name = "tw-energy"
type = "javascript"
account_id = "a35d1765ea70fc364f2336970c9059df"
workers_dev = true

[site]
entry-point = "workers-site"
bucket = "./_site"

[env.staging]
route = "staging.cleanenergyproject.tw/*"
vars = { ENVIRONMENT = "staging" }
zone_id = "d1f4126f8787ef179d51549face1f76e"

[env.production]
bucket = "./_site"
name = "tw-energy-production"
vars = { ENVIRONMENT = "production" }
zone_id = "d1f4126f8787ef179d51549face1f76e"
route = "cleanenergyproject.tw/*"