name = "tw-energy"
type = "javascript"
account_id = "a35d1765ea70fc364f2336970c9059df"
workers_dev = true

[site]
bucket = "./_staging"
entry-point = "workers-site"
route = "staging.cleanenergyproject.tw/*"

[env.production]
bucket = "./_site"
zone_id = "d1f4126f8787ef179d51549face1f76e"
route = "cleanenergyproject.tw/*"