name = "tw-energy-redirects-cache"
type = "javascript"
account_id = "a35d1765ea70fc364f2336970c9059df"
workers_dev = true
route = "cleanenergyproject.tw/*"
zone_id = "d1f4126f8787ef179d51549face1f76e"
